// This file is auto-generated by @hey-api/openapi-ts

export type AnalysesPublic = {
    data: Array<AnalysisPublic>;
    count: number;
};

export type AnalysisCreate = {
    name: string;
    description?: (string | null);
    is_meta?: boolean;
    plane_id?: (string | null);
    collection_id?: (string | null);
    primary_result_id?: (string | null);
    id?: string;
    refs?: Array<AnalysisRefCreate>;
};

export type AnalysisPublic = {
    name: string;
    description?: (string | null);
    is_meta?: boolean;
    plane_id?: (string | null);
    collection_id?: (string | null);
    primary_result_id?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
    refs?: Array<AnalysisRefPublic>;
};

export type AnalysisRefCreate = {
    kind: string;
    entity_id: string;
    id?: string;
};

export type AnalysisRefPublic = {
    kind: string;
    entity_id: string;
    id: string;
};

export type AnalysisUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_meta?: boolean;
    plane_id?: (string | null);
    collection_id?: (string | null);
    primary_result_id?: (string | null);
};

export type AuthConfig = {
    keycloak_url: string;
    keycloak_realm: string;
    keycloak_client_id: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_nomad_add_metadata_to_archive = {
    archive_path: string;
    request_json: string;
};

export type Body_nomad_discard_uploaded_archive = {
    archive_path: string;
};

export type Body_nomad_preview_metadata_from_archive = {
    archive_path: string;
};

export type Body_nomad_upload_to_nomad_endpoint = {
    request_json: string;
    archive_path?: (string | null);
    existing_upload_id?: (string | null);
    files?: (Array<((Blob | File))> | null);
};

/**
 * Full application state for bulk loading.
 */
export type BulkStateResponse = {
    materials: Array<LabMaterialPublic>;
    solutions: Array<LabSolutionPublic>;
    processes: Array<ProcessPublic>;
    experiments: Array<ExperimentPublic>;
    results: Array<ExperimentResultsPublic>;
    analyses: Array<AnalysisPublic>;
    planes: Array<PlanePublic>;
};

export type DataCollectionCreate = {
    i?: number;
    j?: number;
    name: string;
    color?: (string | null);
    id?: string;
};

export type DataCollectionPublic = {
    i?: number;
    j?: number;
    name: string;
    color?: (string | null);
    id: string;
    plane_id: string;
};

export type DataCollectionUpdate = {
    i?: number;
    j?: number;
    name?: (string | null);
    color?: (string | null);
};

export type DeviceGroupCreate = {
    name: string;
    substrate_name?: (string | null);
    assigned_substrate_id?: (string | null);
    suggested_substrate_id?: (string | null);
    match_score?: (number | null);
    id?: string;
};

export type DeviceGroupPublic = {
    name: string;
    substrate_name?: (string | null);
    assigned_substrate_id?: (string | null);
    suggested_substrate_id?: (string | null);
    match_score?: (number | null);
    id: string;
};

export type EntityRefList = {
    ids?: Array<(string)>;
};

export type ExperimentCreate = {
    name: string;
    description?: (string | null);
    notes?: (string | null);
    plane_id?: (string | null);
    collection_id?: (string | null);
    process_id?: (string | null);
    architecture?: (string | null);
    substrate_material?: (string | null);
    substrate_width?: (number | null);
    substrate_length?: (number | null);
    num_substrates?: (number | null);
    devices_per_substrate?: (number | null);
    device_area?: (number | null);
    device_type?: (string | null);
    device_layout_image?: (string | null);
    date?: (string | null);
    end_date?: (string | null);
    has_results?: boolean;
    has_completed_upload?: boolean;
    chemicals_prep?: ({
    [key: string]: unknown;
} | null);
    processing_times?: ({
    [key: string]: unknown;
} | null);
    id?: string;
    substrates?: Array<LabSubstrateCreate>;
};

export type ExperimentMaterialPublic = {
    material_id: string;
    role?: (string | null);
    id: string;
};

export type ExperimentPublic = {
    name: string;
    description?: (string | null);
    notes?: (string | null);
    plane_id?: (string | null);
    collection_id?: (string | null);
    process_id?: (string | null);
    architecture?: (string | null);
    substrate_material?: (string | null);
    substrate_width?: (number | null);
    substrate_length?: (number | null);
    num_substrates?: (number | null);
    devices_per_substrate?: (number | null);
    device_area?: (number | null);
    device_type?: (string | null);
    device_layout_image?: (string | null);
    date?: (string | null);
    end_date?: (string | null);
    has_results?: boolean;
    has_completed_upload?: boolean;
    chemicals_prep?: ({
    [key: string]: unknown;
} | null);
    processing_times?: ({
    [key: string]: unknown;
} | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
    substrates?: Array<LabSubstratePublic>;
    material_refs?: Array<ExperimentMaterialPublic>;
    solution_refs?: Array<ExperimentSolutionPublic>;
};

export type ExperimentResultsCreate = {
    notes?: (string | null);
    plane_id?: (string | null);
    collection_id?: (string | null);
    grouping_strategy?: (string | null);
    matching_strategy?: (string | null);
    nomad_upload_id?: (string | null);
    nomad_upload_time?: (string | null);
    nomad_upload_status?: (string | null);
    nomad_entries?: (number | null);
    id?: string;
    measurement_files?: Array<MeasurementFileCreate>;
    device_groups?: Array<DeviceGroupCreate>;
};

export type ExperimentResultsListPublic = {
    data: Array<ExperimentResultsPublic>;
    count: number;
};

export type ExperimentResultsPublic = {
    notes?: (string | null);
    plane_id?: (string | null);
    collection_id?: (string | null);
    grouping_strategy?: (string | null);
    matching_strategy?: (string | null);
    nomad_upload_id?: (string | null);
    nomad_upload_time?: (string | null);
    nomad_upload_status?: (string | null);
    nomad_entries?: (number | null);
    id: string;
    experiment_id: string;
    owner_id: string;
    created_at?: (string | null);
    measurement_files?: Array<MeasurementFilePublic>;
    device_groups?: Array<DeviceGroupPublic>;
};

export type ExperimentResultsUpdate = {
    notes?: (string | null);
    plane_id?: (string | null);
    collection_id?: (string | null);
    grouping_strategy?: (string | null);
    matching_strategy?: (string | null);
    nomad_upload_id?: (string | null);
    nomad_upload_time?: (string | null);
    nomad_upload_status?: (string | null);
    nomad_entries?: (number | null);
};

export type ExperimentSolutionPublic = {
    solution_id: string;
    role?: (string | null);
    id: string;
};

export type ExperimentsPublic = {
    data: Array<ExperimentPublic>;
    count: number;
};

export type ExperimentUpdate = {
    name?: (string | null);
    description?: (string | null);
    notes?: (string | null);
    plane_id?: (string | null);
    collection_id?: (string | null);
    process_id?: (string | null);
    architecture?: (string | null);
    substrate_material?: (string | null);
    substrate_width?: (number | null);
    substrate_length?: (number | null);
    num_substrates?: (number | null);
    devices_per_substrate?: (number | null);
    device_area?: (number | null);
    device_type?: (string | null);
    device_layout_image?: (string | null);
    date?: (string | null);
    end_date?: (string | null);
    has_results?: boolean;
    has_completed_upload?: boolean;
    chemicals_prep?: ({
    [key: string]: unknown;
} | null);
    processing_times?: ({
    [key: string]: unknown;
} | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LabMaterialCreate = {
    name: string;
    category?: (string | null);
    type?: (string | null);
    cas_number?: (string | null);
    pubchem_cid?: (string | null);
    molecular_weight?: (number | null);
    density?: (number | null);
    density_unit?: string;
    supplier?: (string | null);
    supplier_number?: (string | null);
    inventory_label?: (string | null);
    purity?: (string | null);
    state_at_rt?: (string | null);
    substrate_rigidity?: (string | null);
    height_mm?: (string | null);
    notes?: (string | null);
    plane_id?: (string | null);
    id?: string;
};

export type LabMaterialPublic = {
    name: string;
    category?: (string | null);
    type?: (string | null);
    cas_number?: (string | null);
    pubchem_cid?: (string | null);
    molecular_weight?: (number | null);
    density?: (number | null);
    density_unit?: string;
    supplier?: (string | null);
    supplier_number?: (string | null);
    inventory_label?: (string | null);
    purity?: (string | null);
    state_at_rt?: (string | null);
    substrate_rigidity?: (string | null);
    height_mm?: (string | null);
    notes?: (string | null);
    plane_id?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type LabMaterialsPublic = {
    data: Array<LabMaterialPublic>;
    count: number;
};

export type LabMaterialUpdate = {
    name?: (string | null);
    category?: (string | null);
    type?: (string | null);
    cas_number?: (string | null);
    pubchem_cid?: (string | null);
    molecular_weight?: (number | null);
    density?: (number | null);
    density_unit?: string;
    supplier?: (string | null);
    supplier_number?: (string | null);
    inventory_label?: (string | null);
    purity?: (string | null);
    state_at_rt?: (string | null);
    substrate_rigidity?: (string | null);
    height_mm?: (string | null);
    notes?: (string | null);
    plane_id?: (string | null);
};

export type LabSolutionCreate = {
    name: string;
    type?: (string | null);
    handling?: (string | null);
    storage?: (string | null);
    creation_time?: (string | null);
    notes?: (string | null);
    plane_id?: (string | null);
    id?: string;
    components?: Array<SolutionComponentCreate>;
};

export type LabSolutionPublic = {
    name: string;
    type?: (string | null);
    handling?: (string | null);
    storage?: (string | null);
    creation_time?: (string | null);
    notes?: (string | null);
    plane_id?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
    components?: Array<SolutionComponentPublic>;
};

export type LabSolutionsPublic = {
    data: Array<LabSolutionPublic>;
    count: number;
};

export type LabSolutionUpdate = {
    name?: (string | null);
    type?: (string | null);
    handling?: (string | null);
    storage?: (string | null);
    creation_time?: (string | null);
    notes?: (string | null);
    plane_id?: (string | null);
};

export type LabSubstrateCreate = {
    name: string;
    substrate_material_id?: (string | null);
    notes?: (string | null);
    outcome_status?: (string | null);
    outcome_stopped_at_step?: (string | null);
    outcome_discard_reason?: (string | null);
    parameter_values?: ({
    [key: string]: unknown;
} | null);
    id?: string;
};

export type LabSubstratePublic = {
    name: string;
    substrate_material_id?: (string | null);
    notes?: (string | null);
    outcome_status?: (string | null);
    outcome_stopped_at_step?: (string | null);
    outcome_discard_reason?: (string | null);
    parameter_values?: ({
    [key: string]: unknown;
} | null);
    id: string;
};

export type MeasurementFileCreate = {
    filename: string;
    file_type: string;
    file_path?: (string | null);
    notes?: (string | null);
    device_name?: (string | null);
    cell?: (string | null);
    pixel_label?: (string | null);
    value?: (number | null);
    voc?: (number | null);
    jsc?: (number | null);
    ff?: (number | null);
    measurement_date?: (string | null);
    measurement_user?: (string | null);
    id?: string;
};

export type MeasurementFilePublic = {
    filename: string;
    file_type: string;
    file_path?: (string | null);
    notes?: (string | null);
    device_name?: (string | null);
    cell?: (string | null);
    pixel_label?: (string | null);
    value?: (number | null);
    voc?: (number | null);
    jsc?: (number | null);
    ff?: (number | null);
    measurement_date?: (string | null);
    measurement_user?: (string | null);
    id: string;
};

export type Message = {
    message: string;
};

/**
 * NOMAD configuration status.
 */
export type NomadConfigResponse = {
    enabled: boolean;
    url: string;
    use_global_auth: boolean;
    has_credentials: boolean;
};

/**
 * Response from NOMAD upload.
 */
export type NomadUploadResponse = {
    success: boolean;
    upload_id?: (string | null);
    entry_ids?: Array<(string)>;
    upload_create_time?: (string | null);
    processing_status?: (string | null);
    message?: (string | null);
};

/**
 * Status of a NOMAD upload.
 */
export type NomadUploadStatus = {
    upload_id: string;
    status?: (string | null);
    entries?: (number | Array<{
    [key: string]: unknown;
}> | null);
    last_status_message?: (string | null);
    error?: (string | null);
};

export type PlaneCreate = {
    name: string;
    id?: string;
};

export type PlanePublic = {
    name: string;
    id: string;
    owner_id: string;
    owner: UserPublic;
    created_at?: (string | null);
    sticky_notes?: Array<StickyNotePublic>;
    text_fields?: Array<TextFieldPublic>;
    collections?: Array<DataCollectionPublic>;
    shared_with?: Array<UserPublic>;
};

export type PlaneShareCreate = {
    user_id: string;
};

export type PlanesPublic = {
    data: Array<PlanePublic>;
    count: number;
};

export type PlaneUpdate = {
    name?: (string | null);
};

export type ProcessCreate = {
    name: string;
    description?: (string | null);
    skip_chemistry?: boolean;
    plane_id?: (string | null);
    collection_id?: (string | null);
    id?: string;
};

export type ProcessesPublic = {
    data: Array<ProcessPublic>;
    count: number;
};

export type ProcessGeneratedStackCreate = {
    combination?: number;
    architecture?: (string | null);
    build_device?: (string | null);
    pixel_area_cm2?: (string | null);
    number_of_pixels?: (string | null);
    is_deleted?: boolean;
    id?: string;
    layers?: Array<ProcessGeneratedStackLayerCreate>;
};

export type ProcessGeneratedStackLayerCreate = {
    layer_index?: number;
    name?: string;
    color?: string;
    is_substrate?: boolean;
    layer_type?: string;
    thickness_nm?: string;
    bandgap_ev?: string;
    perovskite_a?: string;
    perovskite_b?: string;
    perovskite_x?: string;
    id?: string;
};

export type ProcessGeneratedStackLayerPublic = {
    layer_index?: number;
    name?: string;
    color?: string;
    is_substrate?: boolean;
    layer_type?: string;
    thickness_nm?: string;
    bandgap_ev?: string;
    perovskite_a?: string;
    perovskite_b?: string;
    perovskite_x?: string;
    id: string;
};

export type ProcessGeneratedStackPublic = {
    combination?: number;
    architecture?: (string | null);
    build_device?: (string | null);
    pixel_area_cm2?: (string | null);
    number_of_pixels?: (string | null);
    is_deleted?: boolean;
    id: string;
    layers?: Array<ProcessGeneratedStackLayerPublic>;
};

export type ProcessInlineSubstrateCreate = {
    name: string;
    rigidity?: (string | null);
    length_cm?: (string | null);
    width_cm?: (string | null);
    height_mm?: (string | null);
    surface_roughness_rms_nm?: (string | null);
    id?: string;
};

export type ProcessInlineSubstratePublic = {
    name: string;
    rigidity?: (string | null);
    length_cm?: (string | null);
    width_cm?: (string | null);
    height_mm?: (string | null);
    surface_roughness_rms_nm?: (string | null);
    id: string;
};

export type ProcessPublic = {
    name: string;
    description?: (string | null);
    skip_chemistry?: boolean;
    plane_id?: (string | null);
    collection_id?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
    inline_substrates?: Array<ProcessInlineSubstratePublic>;
    substrate_dimensions?: Array<ProcessSubstrateDimensionPublic>;
    recipes?: Array<ProcessSolutionRecipePublic>;
    steps?: Array<ProcessStepPublic>;
    stacks?: Array<ProcessGeneratedStackPublic>;
};

export type ProcessSolutionRecipeCreate = {
    name: string;
    type?: (string | null);
    is_commercial?: boolean;
    commercial_name?: (string | null);
    supplier_number?: (string | null);
    handling_preparation?: (string | null);
    handling_before_use?: (string | null);
    total_solvent_volume_ml?: string;
    id?: string;
    solvents?: Array<RecipeSolventCreate>;
    solutes?: Array<RecipeSoluteCreate>;
    added_solutions?: Array<RecipeAddedSolutionCreate>;
};

export type ProcessSolutionRecipePublic = {
    name: string;
    type?: (string | null);
    is_commercial?: boolean;
    commercial_name?: (string | null);
    supplier_number?: (string | null);
    handling_preparation?: (string | null);
    handling_before_use?: (string | null);
    total_solvent_volume_ml?: string;
    id: string;
    solvents?: Array<RecipeSolventPublic>;
    solutes?: Array<RecipeSolutePublic>;
    added_solutions?: Array<RecipeAddedSolutionPublic>;
};

export type ProcessStepCreate = {
    stage_index?: number;
    step_index?: number;
    name: string;
    step_category: string;
    color?: string;
    material_id?: (string | null);
    solution_id?: (string | null);
    chem_recipe_id?: (string | null);
    inline_material?: ({
    [key: string]: unknown;
} | null);
    deposition_method_value?: (string | null);
    deposition_method_mode?: (string | null);
    deposition_start_time_value?: (string | null);
    deposition_start_time_mode?: (string | null);
    substrate_temp_value?: (string | null);
    substrate_temp_mode?: (string | null);
    deposition_atmosphere_value?: (string | null);
    deposition_atmosphere_mode?: (string | null);
    deposition_parameters_value?: (string | null);
    deposition_parameters_mode?: (string | null);
    solution_volume_value?: (string | null);
    solution_volume_mode?: (string | null);
    drying_method_value?: (string | null);
    drying_method_mode?: (string | null);
    annealing_start_time_value?: (string | null);
    annealing_start_time_mode?: (string | null);
    annealing_time_value?: (string | null);
    annealing_time_mode?: (string | null);
    annealing_temp_value?: (string | null);
    annealing_temp_mode?: (string | null);
    annealing_atmosphere_value?: (string | null);
    annealing_atmosphere_mode?: (string | null);
    notes?: (string | null);
    id?: string;
};

export type ProcessStepPublic = {
    stage_index?: number;
    step_index?: number;
    name: string;
    step_category: string;
    color?: string;
    material_id?: (string | null);
    solution_id?: (string | null);
    chem_recipe_id?: (string | null);
    inline_material?: ({
    [key: string]: unknown;
} | null);
    deposition_method_value?: (string | null);
    deposition_method_mode?: (string | null);
    deposition_start_time_value?: (string | null);
    deposition_start_time_mode?: (string | null);
    substrate_temp_value?: (string | null);
    substrate_temp_mode?: (string | null);
    deposition_atmosphere_value?: (string | null);
    deposition_atmosphere_mode?: (string | null);
    deposition_parameters_value?: (string | null);
    deposition_parameters_mode?: (string | null);
    solution_volume_value?: (string | null);
    solution_volume_mode?: (string | null);
    drying_method_value?: (string | null);
    drying_method_mode?: (string | null);
    annealing_start_time_value?: (string | null);
    annealing_start_time_mode?: (string | null);
    annealing_time_value?: (string | null);
    annealing_time_mode?: (string | null);
    annealing_temp_value?: (string | null);
    annealing_temp_mode?: (string | null);
    annealing_atmosphere_value?: (string | null);
    annealing_atmosphere_mode?: (string | null);
    notes?: (string | null);
    id: string;
};

export type ProcessSubstrateDimensionCreate = {
    material_id: string;
    length_cm?: (string | null);
    width_cm?: (string | null);
    height_mm?: (string | null);
    surface_roughness_rms_nm?: (string | null);
    id?: string;
};

export type ProcessSubstrateDimensionPublic = {
    material_id: string;
    length_cm?: (string | null);
    width_cm?: (string | null);
    height_mm?: (string | null);
    surface_roughness_rms_nm?: (string | null);
    id: string;
};

export type ProcessUpdate = {
    name?: (string | null);
    description?: (string | null);
    skip_chemistry?: boolean;
    plane_id?: (string | null);
    collection_id?: (string | null);
};

export type RecipeAddedSolutionCreate = {
    referenced_recipe_id?: (string | null);
    volume_ml?: string;
    id?: string;
};

export type RecipeAddedSolutionPublic = {
    referenced_recipe_id?: (string | null);
    volume_ml?: string;
    id: string;
};

export type RecipeSoluteCreate = {
    name: string;
    pubchem_cid?: (string | null);
    component_cids?: (Array<(string)> | null);
    molar_mass?: (number | null);
    density?: (number | null);
    amount?: string;
    unit?: string;
    color?: string;
    id?: string;
};

export type RecipeSolutePublic = {
    name: string;
    pubchem_cid?: (string | null);
    component_cids?: (Array<(string)> | null);
    molar_mass?: (number | null);
    density?: (number | null);
    amount?: string;
    unit?: string;
    color?: string;
    id: string;
};

export type RecipeSolventCreate = {
    name: string;
    pubchem_cid?: (string | null);
    component_cids?: (Array<(string)> | null);
    molar_mass?: (number | null);
    density?: (number | null);
    volume_ratio?: number;
    color?: string;
    id?: string;
};

export type RecipeSolventPublic = {
    name: string;
    pubchem_cid?: (string | null);
    component_cids?: (Array<(string)> | null);
    molar_mass?: (number | null);
    density?: (number | null);
    volume_ratio?: number;
    color?: string;
    id: string;
};

export type SolutionComponentCreate = {
    amount: number;
    unit: string;
    material_id?: (string | null);
    solution_ref_id?: (string | null);
    id?: string;
};

export type SolutionComponentPublic = {
    amount: number;
    unit: string;
    material_id?: (string | null);
    solution_ref_id?: (string | null);
    id: string;
};

export type StickyNoteCreate = {
    i?: number;
    j?: number;
    di?: number;
    dj?: number;
    content?: (string | null);
    color?: (string | null);
    fmt_bold?: (boolean | null);
    fmt_italic?: (boolean | null);
    fmt_underline?: (boolean | null);
    fmt_font_size?: (number | null);
    hyperlink?: (string | null);
    id?: string;
};

export type StickyNotePublic = {
    i?: number;
    j?: number;
    di?: number;
    dj?: number;
    content?: (string | null);
    color?: (string | null);
    fmt_bold?: (boolean | null);
    fmt_italic?: (boolean | null);
    fmt_underline?: (boolean | null);
    fmt_font_size?: (number | null);
    hyperlink?: (string | null);
    id: string;
    plane_id: string;
};

export type StickyNoteUpdate = {
    i?: number;
    j?: number;
    di?: number;
    dj?: number;
    content?: (string | null);
    color?: (string | null);
    fmt_bold?: (boolean | null);
    fmt_italic?: (boolean | null);
    fmt_underline?: (boolean | null);
    fmt_font_size?: (number | null);
    hyperlink?: (string | null);
};

export type TextFieldCreate = {
    i?: number;
    j?: number;
    di?: number;
    dj?: number;
    content?: (string | null);
    color?: (string | null);
    fmt_bold?: (boolean | null);
    fmt_italic?: (boolean | null);
    fmt_underline?: (boolean | null);
    fmt_font_size?: (number | null);
    hyperlink?: (string | null);
    id?: string;
};

export type TextFieldPublic = {
    i?: number;
    j?: number;
    di?: number;
    dj?: number;
    content?: (string | null);
    color?: (string | null);
    fmt_bold?: (boolean | null);
    fmt_italic?: (boolean | null);
    fmt_underline?: (boolean | null);
    fmt_font_size?: (number | null);
    hyperlink?: (string | null);
    id: string;
    plane_id: string;
};

export type TextFieldUpdate = {
    i?: number;
    j?: number;
    di?: number;
    dj?: number;
    content?: (string | null);
    color?: (string | null);
    fmt_bold?: (boolean | null);
    fmt_italic?: (boolean | null);
    fmt_underline?: (boolean | null);
    fmt_font_size?: (number | null);
    hyperlink?: (string | null);
};

export type Token = {
    access_token: string;
    token_type: string;
};

export type UiPrefsUpdate = {
    ui_prefs: {
        [key: string]: unknown;
    };
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserStatePublic = {
    data: {
        [key: string]: unknown;
    };
    updated_at?: (string | null);
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AnalysesReadAnalysesData = {
    limit?: number;
    skip?: number;
};

export type AnalysesReadAnalysesResponse = (AnalysesPublic);

export type AnalysesCreateAnalysisData = {
    requestBody: AnalysisCreate;
};

export type AnalysesCreateAnalysisResponse = (AnalysisPublic);

export type AnalysesReadAnalysisData = {
    id: string;
};

export type AnalysesReadAnalysisResponse = (AnalysisPublic);

export type AnalysesUpdateAnalysisData = {
    id: string;
    requestBody: AnalysisUpdate;
};

export type AnalysesUpdateAnalysisResponse = (AnalysisPublic);

export type AnalysesDeleteAnalysisData = {
    id: string;
};

export type AnalysesDeleteAnalysisResponse = (unknown);

export type ExperimentsReadExperimentsData = {
    limit?: number;
    skip?: number;
};

export type ExperimentsReadExperimentsResponse = (ExperimentsPublic);

export type ExperimentsCreateItemData = {
    requestBody: ExperimentCreate;
};

export type ExperimentsCreateItemResponse = (ExperimentPublic);

export type ExperimentsReadExperimentData = {
    id: string;
};

export type ExperimentsReadExperimentResponse = (ExperimentPublic);

export type ExperimentsUpdateItemData = {
    id: string;
    requestBody: ExperimentUpdate;
};

export type ExperimentsUpdateItemResponse = (ExperimentPublic);

export type ExperimentsDeleteExperimentData = {
    id: string;
};

export type ExperimentsDeleteExperimentResponse = (unknown);

export type ExperimentsSetExperimentMaterialsData = {
    id: string;
    requestBody: EntityRefList;
};

export type ExperimentsSetExperimentMaterialsResponse = (ExperimentPublic);

export type ExperimentsSetExperimentSolutionsData = {
    id: string;
    requestBody: EntityRefList;
};

export type ExperimentsSetExperimentSolutionsResponse = (ExperimentPublic);

export type ExperimentsReplaceExperimentSubstratesData = {
    id: string;
    requestBody: Array<LabSubstrateCreate>;
};

export type ExperimentsReplaceExperimentSubstratesResponse = (Array<LabSubstratePublic>);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginAuthConfigResponse = (AuthConfig);

export type MaterialsReadMaterialsData = {
    limit?: number;
    skip?: number;
};

export type MaterialsReadMaterialsResponse = (LabMaterialsPublic);

export type MaterialsCreateMaterialData = {
    requestBody: LabMaterialCreate;
};

export type MaterialsCreateMaterialResponse = (LabMaterialPublic);

export type MaterialsReadMaterialData = {
    id: string;
};

export type MaterialsReadMaterialResponse = (LabMaterialPublic);

export type MaterialsUpdateMaterialData = {
    id: string;
    requestBody: LabMaterialUpdate;
};

export type MaterialsUpdateMaterialResponse = (LabMaterialPublic);

export type MaterialsDeleteMaterialData = {
    id: string;
};

export type MaterialsDeleteMaterialResponse = (unknown);

export type NomadGetNomadConfigResponse = (NomadConfigResponse);

export type NomadUploadFilesForNomadResponse = ({
    [key: string]: unknown;
});

export type NomadAddMetadataToArchiveData = {
    formData: Body_nomad_add_metadata_to_archive;
};

export type NomadAddMetadataToArchiveResponse = ({
    [key: string]: unknown;
});

export type NomadPreviewMetadataFromArchiveData = {
    formData: Body_nomad_preview_metadata_from_archive;
};

export type NomadPreviewMetadataFromArchiveResponse = ({
    [key: string]: unknown;
});

export type NomadDiscardUploadedArchiveData = {
    formData: Body_nomad_discard_uploaded_archive;
};

export type NomadDiscardUploadedArchiveResponse = ({
    [key: string]: unknown;
});

export type NomadUploadToNomadEndpointData = {
    formData: Body_nomad_upload_to_nomad_endpoint;
};

export type NomadUploadToNomadEndpointResponse = (NomadUploadResponse);

export type NomadCheckUploadStatusData = {
    uploadId: string;
};

export type NomadCheckUploadStatusResponse = (NomadUploadStatus);

export type NomadTestNomadAuthResponse = ({
    [key: string]: unknown;
});

export type PlanesReadPlanesData = {
    limit?: number;
    skip?: number;
};

export type PlanesReadPlanesResponse = (PlanesPublic);

export type PlanesCreatePlaneData = {
    requestBody: PlaneCreate;
};

export type PlanesCreatePlaneResponse = (PlanePublic);

export type PlanesReadPlaneData = {
    id: string;
};

export type PlanesReadPlaneResponse = (PlanePublic);

export type PlanesUpdatePlaneData = {
    id: string;
    requestBody: PlaneUpdate;
};

export type PlanesUpdatePlaneResponse = (PlanePublic);

export type PlanesDeletePlaneData = {
    id: string;
};

export type PlanesDeletePlaneResponse = (unknown);

export type PlanesSharePlaneData = {
    id: string;
    requestBody: PlaneShareCreate;
};

export type PlanesSharePlaneResponse = (PlanePublic);

export type PlanesUnsharePlaneData = {
    id: string;
    userId: string;
};

export type PlanesUnsharePlaneResponse = (PlanePublic);

export type PlanesSearchUsersData = {
    limit?: number;
    q?: string;
};

export type PlanesSearchUsersResponse = (Array<UserPublic>);

export type PlanesCreateStickyNoteData = {
    planeId: string;
    requestBody: StickyNoteCreate;
};

export type PlanesCreateStickyNoteResponse = (StickyNotePublic);

export type PlanesReplaceStickyNotesData = {
    planeId: string;
    requestBody: Array<StickyNoteCreate>;
};

export type PlanesReplaceStickyNotesResponse = (Array<StickyNotePublic>);

export type PlanesUpdateStickyNoteData = {
    noteId: string;
    planeId: string;
    requestBody: StickyNoteUpdate;
};

export type PlanesUpdateStickyNoteResponse = (StickyNotePublic);

export type PlanesDeleteStickyNoteData = {
    noteId: string;
    planeId: string;
};

export type PlanesDeleteStickyNoteResponse = (unknown);

export type PlanesCreateTextFieldData = {
    planeId: string;
    requestBody: TextFieldCreate;
};

export type PlanesCreateTextFieldResponse = (TextFieldPublic);

export type PlanesReplaceTextFieldsData = {
    planeId: string;
    requestBody: Array<TextFieldCreate>;
};

export type PlanesReplaceTextFieldsResponse = (Array<TextFieldPublic>);

export type PlanesUpdateTextFieldData = {
    fieldId: string;
    planeId: string;
    requestBody: TextFieldUpdate;
};

export type PlanesUpdateTextFieldResponse = (TextFieldPublic);

export type PlanesDeleteTextFieldData = {
    fieldId: string;
    planeId: string;
};

export type PlanesDeleteTextFieldResponse = (unknown);

export type PlanesCreateCollectionData = {
    planeId: string;
    requestBody: DataCollectionCreate;
};

export type PlanesCreateCollectionResponse = (DataCollectionPublic);

export type PlanesReplaceCollectionsData = {
    planeId: string;
    requestBody: Array<DataCollectionCreate>;
};

export type PlanesReplaceCollectionsResponse = (Array<DataCollectionPublic>);

export type PlanesUpdateCollectionData = {
    collectionId: string;
    planeId: string;
    requestBody: DataCollectionUpdate;
};

export type PlanesUpdateCollectionResponse = (DataCollectionPublic);

export type PlanesDeleteCollectionData = {
    collectionId: string;
    planeId: string;
};

export type PlanesDeleteCollectionResponse = (unknown);

export type ProcessesReadProcessesData = {
    limit?: number;
    skip?: number;
};

export type ProcessesReadProcessesResponse = (ProcessesPublic);

export type ProcessesCreateProcessData = {
    requestBody: ProcessCreate;
};

export type ProcessesCreateProcessResponse = (ProcessPublic);

export type ProcessesReadProcessData = {
    id: string;
};

export type ProcessesReadProcessResponse = (ProcessPublic);

export type ProcessesUpdateProcessData = {
    id: string;
    requestBody: ProcessUpdate;
};

export type ProcessesUpdateProcessResponse = (ProcessPublic);

export type ProcessesDeleteProcessData = {
    id: string;
};

export type ProcessesDeleteProcessResponse = (unknown);

export type ProcessesReadProcessRecipesData = {
    id: string;
};

export type ProcessesReadProcessRecipesResponse = (unknown);

export type ProcessesCreateProcessRecipeData = {
    id: string;
    requestBody: ProcessSolutionRecipeCreate;
};

export type ProcessesCreateProcessRecipeResponse = (ProcessSolutionRecipePublic);

export type ProcessesReplaceProcessRecipesData = {
    id: string;
    requestBody: Array<ProcessSolutionRecipeCreate>;
};

export type ProcessesReplaceProcessRecipesResponse = (Array<ProcessSolutionRecipePublic>);

export type ProcessesUpdateProcessRecipeData = {
    id: string;
    requestBody: ProcessSolutionRecipeCreate;
    rid: string;
};

export type ProcessesUpdateProcessRecipeResponse = (ProcessSolutionRecipePublic);

export type ProcessesDeleteProcessRecipeData = {
    id: string;
    rid: string;
};

export type ProcessesDeleteProcessRecipeResponse = (unknown);

export type ProcessesReadProcessStepsData = {
    id: string;
};

export type ProcessesReadProcessStepsResponse = (unknown);

export type ProcessesCreateProcessStepData = {
    id: string;
    requestBody: ProcessStepCreate;
};

export type ProcessesCreateProcessStepResponse = (ProcessStepPublic);

export type ProcessesReplaceProcessStepsData = {
    id: string;
    requestBody: Array<ProcessStepCreate>;
};

export type ProcessesReplaceProcessStepsResponse = (Array<ProcessStepPublic>);

export type ProcessesUpdateProcessStepData = {
    id: string;
    requestBody: ProcessStepCreate;
    sid: string;
};

export type ProcessesUpdateProcessStepResponse = (ProcessStepPublic);

export type ProcessesDeleteProcessStepData = {
    id: string;
    sid: string;
};

export type ProcessesDeleteProcessStepResponse = (unknown);

export type ProcessesReadProcessStacksData = {
    id: string;
};

export type ProcessesReadProcessStacksResponse = (unknown);

export type ProcessesCreateProcessStackData = {
    id: string;
    requestBody: ProcessGeneratedStackCreate;
};

export type ProcessesCreateProcessStackResponse = (ProcessGeneratedStackPublic);

export type ProcessesReplaceProcessStacksData = {
    id: string;
    requestBody: Array<ProcessGeneratedStackCreate>;
};

export type ProcessesReplaceProcessStacksResponse = (Array<ProcessGeneratedStackPublic>);

export type ProcessesUpdateProcessStackData = {
    id: string;
    requestBody: ProcessGeneratedStackCreate;
    stackId: string;
};

export type ProcessesUpdateProcessStackResponse = (ProcessGeneratedStackPublic);

export type ProcessesDeleteProcessStackData = {
    id: string;
    stackId: string;
};

export type ProcessesDeleteProcessStackResponse = (unknown);

export type ProcessesReadProcessInlineSubstratesData = {
    id: string;
};

export type ProcessesReadProcessInlineSubstratesResponse = (unknown);

export type ProcessesReplaceProcessInlineSubstratesData = {
    id: string;
    requestBody: Array<ProcessInlineSubstrateCreate>;
};

export type ProcessesReplaceProcessInlineSubstratesResponse = (Array<ProcessInlineSubstratePublic>);

export type ProcessesReadProcessSubstrateDimensionsData = {
    id: string;
};

export type ProcessesReadProcessSubstrateDimensionsResponse = (unknown);

export type ProcessesReplaceProcessSubstrateDimensionsData = {
    id: string;
    requestBody: Array<ProcessSubstrateDimensionCreate>;
};

export type ProcessesReplaceProcessSubstrateDimensionsResponse = (Array<ProcessSubstrateDimensionPublic>);

export type ResultsReadResultsData = {
    limit?: number;
    skip?: number;
};

export type ResultsReadResultsResponse = (ExperimentResultsListPublic);

export type ResultsCreateResultData = {
    experimentId: string;
    requestBody: ExperimentResultsCreate;
};

export type ResultsCreateResultResponse = (ExperimentResultsPublic);

export type ResultsReadResultData = {
    id: string;
};

export type ResultsReadResultResponse = (ExperimentResultsPublic);

export type ResultsUpdateResultData = {
    id: string;
    requestBody: ExperimentResultsUpdate;
};

export type ResultsUpdateResultResponse = (ExperimentResultsPublic);

export type ResultsDeleteResultData = {
    id: string;
};

export type ResultsDeleteResultResponse = (unknown);

export type ResultsReplaceMeasurementFilesData = {
    id: string;
    requestBody: Array<MeasurementFileCreate>;
};

export type ResultsReplaceMeasurementFilesResponse = (Array<MeasurementFilePublic>);

export type ResultsReplaceDeviceGroupsData = {
    id: string;
    requestBody: Array<DeviceGroupCreate>;
};

export type ResultsReplaceDeviceGroupsResponse = (Array<DeviceGroupPublic>);

export type SolutionsReadSolutionsData = {
    limit?: number;
    skip?: number;
};

export type SolutionsReadSolutionsResponse = (LabSolutionsPublic);

export type SolutionsCreateItemData = {
    requestBody: LabSolutionCreate;
};

export type SolutionsCreateItemResponse = (LabSolutionPublic);

export type SolutionsReadSolutionData = {
    id: string;
};

export type SolutionsReadSolutionResponse = (LabSolutionPublic);

export type SolutionsUpdateItemData = {
    id: string;
    requestBody: LabSolutionUpdate;
};

export type SolutionsUpdateItemResponse = (LabSolutionPublic);

export type SolutionsDeleteSolutionData = {
    id: string;
};

export type SolutionsDeleteSolutionResponse = (unknown);

export type StateReadStateResponse = (UserStatePublic);

export type StateUpdateStateData = {
    requestBody: UiPrefsUpdate;
};

export type StateUpdateStateResponse = (UserStatePublic);

export type StateGetBulkStateResponse = (BulkStateResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);